# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=2083)),
                ('click', models.CharField(max_length=2083)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafa.Site'),
        ),
        migrations.AddField(
            model_name='advert',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafa.Zone'),
        ),
    ]
