# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yafa', '0003_advert_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
