# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    replaces = [(b'yafa', '0005_auto_20160808_1946'), (b'yafa', '0006_auto_20160808_1956')]

    dependencies = [
        ('yafa', '0004_advert_active'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchicalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='yafa.HierarchicalTag')),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yafa_taggedadvert_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('object_id', models.IntegerField(db_index=True, default=1, verbose_name='Object id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='advert',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='yafa.TaggedAdvert', to='yafa.HierarchicalTag', verbose_name='Tags'),
        ),
    ]
