# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yafa', '0005_auto_20160808_1946_squashed_0006_auto_20160808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='taggedadvert',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yafa_taggedadvert_tagged_items', to='contenttypes.ContentType', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='taggedadvert',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='Object id'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
